name: Release Drafter
on:
    push:
        branches: [staging]
    workflow_dispatch:
        inputs:
            previous-version:
                description: What release to use as a base for release note purposes
                required: false
                type: string
concurrency: ${{ github.workflow }}
jobs:
    draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@219b17038f47a488197914b7d8f813de08677fc5 # v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  disable-autolabeler: true
                  previous-version: ${{ inputs.previous-version }}
